repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
    - id: yapf
      args: ['--parallel', '--in-place']
