name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.4]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2.3.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jax[cpu]
        pip install .[test]

    - name: Run tests
      run: |
        cd tests
        export JAX_PLATFORM_NAME=cpu
        export XLA_FLAGS='--xla_force_host_platform_device_count=8'
        pytest -v
